blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/<your-org>/<your-repo>/discussions
    about: For open-ended discussion, please use GitHub Discussions instead of Issues.
