name: "Report an Error"
description: Report a factual error, broken link, or formatting issue in the documentation
title: "[Error]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Found something wrong? Please help us fix it by describing the issue below.

  - type: input
    id: location
    attributes:
      label: Location
      description: Which file or section does this affect?
      placeholder: "e.g., docs/methodology/calculations.md, Section 2.3"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: What exactly is wrong (typo, broken link, incorrect formula, etc.)?
      placeholder: "e.g., Equation 2 is missing a denominator term."
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested correction
      description: If you know the fix, propose it here.
      placeholder: "e.g., Replace with `E = A * EF / 1000`"
    validations:
      required: false
